function cambiar_fondo_con_class(){
    d = new Date();
    t = d.getHours();
    r = Math.round((Math.random() * 3.99) - 0.5);

    if (t == 0) {hora = 'es media noche'}
    else if (t == 1) {hora = 'es la una de la mañana'}
    else if (t == 2) {hora = 'son las dos de la mañana'}
    else if (t == 3) {hora = 'son las tres de la mañana'}
    else if (t == 4) {hora = 'son las cuatro de la mañana'}
    else if (t == 5) {hora = 'Son las cinco de la mañana'}
    else if (t == 6) {hora = 'Son las seis de la mañana'}
    else if (t == 7) {hora = 'Son las siete de la mañana'}
    else if (t == 8) {hora = 'Son las ocho de la mañana'}
    else if (t == 9) {hora = 'Son las nueve de la mañana'}
    else if (t == 10) {hora = 'Son las diez'}
    else if (t == 11) {hora = 'son las once'}
    else if (t == 12) {hora = 'es medio día'}
    else if (t == 13) {hora = 'es la una de la tarde'}
    else if (t == 14) {hora = 'son las dos'}
    else if (t == 15) {hora = 'son las tres'}
    else if (t == 16) {hora = 'son las cuatro'}
    else if (t == 17) {hora = 'son las cinco'}
    else if (t == 18) {hora = 'son las seis'}
    else if (t == 19) {hora = 'son las siete'}
    else if (t == 20) {hora = 'son las ocho'}
    else if (t == 21) {hora = 'son las nueve'}
    else if (t == 22) {hora = 'son las diez'}
    else if (t == 23) {hora = 'son las once'}
    
    parrafo0 = "Princesa hermosa " + hora + " ¿qué haces despierta tan tarde😥? ¿no puedes dormir😥? desearía tanto estar ahí contigo abrazándote y dándote calorcito para que pudieras dormir más fácil😢. Aunque seguramente yo estaría más que dormido🙈 pero aún dormido te abrazaría muy fuerte y no te soltaría😘😘. No puedo esperar al día que por fin durmamos en la misma cama🤩. <br> <br>En este momento debo estar soñando contigo😴 y tú deberías estar haciendo lo mismo😪. Pero, ya que estas despierta quiero decirte que soy muy afortunado de que seas mi novia😍😍. Tú eres la novia perfecta y no me cabe la más mínima duda de eso. Me has dado tanto, sin pedir nunca nada a cambio y es por eso que quiero dártelo todo💖💖. Quiero darte todo lo que desees y más, quiero hacerte vivir aventuras de todo tipo.  <br> <br>Algún día iremos a ver la aurora boreal juntos🤩. Te imaginas que viajemos🛫, pasemos frio❄, acampemos⛺, nos desvelemos y nos pongamos a ver sentaditos ese espectáculo✨ de luces🤩🤩. Tan solo con pensarlo se me escapa una sonrisa y sé que a ti también😁. No hay nadie más en este mundo con quien quisiera compartir un momento así😘. Y no solo conformarnos con la aurora boreal, quiero que nos pongamos miles de retos🤩 y los cumplamos agarrados de la mano🤝. Me hace muy feliz soñar con un futuro a tu lado💖.<br> <br>Ya deberías intentar dormir un poco mi amor😅, no es bueno que te desveles. Pero, antes de que te duermas pasate por la sección de imágenes. Me dijeron que hay muchas fotitos de un chico muy guapo allí😍😍. Si encuentras una foto mía durmiendo😴, quedate viéndola e imagina que estoy así durmiendo al frente tuyo. Dame un besito😘 y duerme conmigo, Te amo mi princesa💖...";
    parrafo1 = hora + " ¿Cómo amaneció la niñita más hermosa y maravillosa del mundo😍😍? ¿Soñaste cositas lindas🤩? ¿cositas pervertidas🔥🔥? ¿o tal vez tuviste una pesadilla😥?  en cualquier caso escríbeme y cuéntame. Si estuviera ahí te daría muchos besitos😘😘 de buenos días y no dejaría que te pararas de la cama. Me la pasaría debajo de la sabana jalandote para que te quedes conmigo🙈.<br><br> Hoy va a ser un día maravilloso✨, te ves hermosa por cierto😍. Si vas a salir recuerda que tienes un novio que te adora mucho y se muere por ti💖. También hazme un favor canta en la ducha🎶🎶, sonríele al espejo😁, baila mientras te vistes💃 y desayuna algo muy rico🤤. Hay que empezar el día con buen pie, así que quiero que hagas todo eso😘😘. Pero sobre todo quiero que me sientas ahí a tu lado🤗, como te miro mientras te arreglas😍, mientras desayunas y como se me escapa una sonrisa al verte😍.<br><br>Me encantaría llevarte a lugares sorprendentes para que despertemos viendo las montañas🏞 o ver el amanecer desde un globo aerodinámico, tal vez algún día tengamos la oportunidad😢. Sé que eso te haría muy feliz, aunque yo me conformo con verte sonreír todas las mañanas😘. También te haría un rapidín antes de irme a trabajar😅🔥.<br><br> Eres mi niñita consentida y quiero hacer todas tus mañanas fantásticas🤩. Que todos los días te sientas feliz de haberme elegido como tu compañero de vida🤗. Quiero que sientas que puedes lograr lo que sea y que eres inigualable, porque en verdad lo eres. Te amo mi niñita perfecta💖💖. ";
    parrafo2 = "Ya " + hora + " amor, en verdad espero que tu día este yendo de maravilla hasta ahorita😊. Si te acabas de despertar, me alegra mucho que duermas hasta esta hora🤭. ¿Ya almorzaste🤔? mmmm... Come algo!😠 y recuerda beber mucha agua😘😘. Si andas en la calle cuidate mucho😥, tú eres lo más valioso en mi vida, eres mi tesoro. Te mando miles de besitos😘😘 y abrazos🤗, imagina que estoy allí agarrando tu mano🤝 mientras haces todo lo que tengas que hacer en el día🤩.<br><br>Escríbeme que estas haciendo por favor😍, si es día de semana y estoy trabajando puede que tarde en responder🙈🙈 pero te aseguro que estoy pendiente de ti😘. Me hace muy feliz💖 recibir mensajes tuyos mi amor😍, especialmente si me dices cositas bonitas😍. Amo ser tu novio😍, amo saber que cuento contigo😍, amo poder confiar en ti con mi vida😍 y sobre todo amo verte sonreír😍😍. <br><br>Adoraría poder pasear contigo agarrados🤝 de la mano, ir a plazas, restaurantes, cafés, caminar por las calles👫, cruzar puentes, encontrar un jardín lleno de flores y apreciarlas😍. Tú y yo juntos siempre💏, paseando por toda la ciudad y descubriendo nuevos lugares que visitar🤩. No sé donde viviremos, no sé en que país ni en que ciudad. Pero, en la que sea debemos recorrerla bien y salir a comer a un lugar nuevo cada semana🤩. <br><br>Estoy Seguro de que este día te aguarda uno de esos momentos de felicidad😘, puede ser algo muy grande, como un regalo🎁, o algo muy leve, como ver un niño sonreír al caminar👶. Así que estate atenta a ese momento y si encuentras algo hoy que te hizo feliz💖, ya sabes, cuéntamelo😘😘...";
    parrafo3 = "Mi cielo ya " + hora + ", ¿Qué haces🤔? ¿Qué has estado haciendo en el día🤔? te extraño demasiado😭. No sé si ya te lo dije hoy pero por si acaso se me olvidó: Eres la más hermosa del mundo mi princesa😍😍😍. Estoy deseando llenarte enterita de besitos😘😘 y lamiditas😋😋. Lo que sea que estes haciendo recuerda que este mundo es un lugar mejor solo porque tú estas en él😍. <br><br>Seguro te gustaría estar en la playa en este momento🙈 y a mí me encantaría estar ahí acompañándote😍. Viendo el atardecer juntitos en la arena🏝. Te prometo que lo haremos🤩, que veremos ese atardecer🌤, comeremos sanguchitos🥪, nos broncearemos y nadaremos en la playa🏊‍♂️. Sé cuanto amas la playa y es mi deseo llevarte a millones de playa diferentes😍😍.<br><br>Aunque ahorita no estemos en la playa, no te desanimes😥, aún hay muchas cosas buenas a tu alrededor. Sonríe mucho🤩, especialmente cerca de las personas que amas💖. Tu sonrisa es más hermosa que cualquier otra cosa😍, no te imaginas lo que daría por estar viéndola ahorita mismo😭. Si estas leyendo esto por favor escríbeme cuanto me amas😭 y cuanto deseas estar a mi lado😭, eso me da ánimos para seguir con mi día🤩🤩. <br><br>Te necesito demasiado mi cielo😢, necesito tus caricias😢, tus besos😢, tus abrazos😢 y tus mimos😢. Te necesito tanto y sé que tú a mí también😢, lamento mucho no estar a tu lado en este momento😔, pero jamás te dejaré sola mi princesa😢 y si quieres sentirme más cerquita pasate por la sección de imágenes🤩 y por cada imagen que veas que te doy un besito😘😘, te estaré dedicando un TE AMO💖💖...";
    parrafo4 = "Mi vida preciosa💖 " + hora + ", ya se hizo de noche!🌖 Esta es la hora del día en que hablamos y nos contamos todo lo que hicimos😍. Si aún no has hablado conmigo llamame🤩 y cuéntame sobre tu día, me encanta escucharte😍. Si ya me llamaste y me dormí temprano perdón🙈🙈, los pingüinitos🐧 tendemos a dormir tempranito🐧😴. Te juro que amo conversar contigo de todo😍, es bastante liberador tener a alguien a quien contarle lo que sea😍💖.<br><br>Esta noche la luna🌔 se ve hermosa (pero nunca más hermosa que tú🙈). Seguro que así como yo, tú también ves la luna, las estrellas y piensas en mí😍. A pesar de la distancia que nos separa, somos la pareja más unida que conozco😍 y quiero que sea así toda la vida😍. Me llena de alegría pensar en ti antes de dormir😍, pensar en ese momento cuando nos veamos cara a cara💖, cuando te diga que te amo💖💖 y que te he extrañado como loco💖💖💖. <br><br>Esa primera noche que pasemos juntos quiero que nos tomemos un tiempo para ver las luces de la ciudad🌆. Con cada ciudad nueva que visitemos haremos lo mismo🌆, la primera noche nos dedicaremos un tiempo para admirar el paisaje de noche😍🌆. Te abrazaría mientras nos asomamos por la ventana😍 y te diría que eres el amor de mi vida💖. Deseo visitar tantas ciudades contigo💖, conocer decenas de países💖 y caminar por cientos de pueblos diferentes🤩. <br><br> Mi vida todas las noches te agradezco por ser mi novia💖💖 y es que ser tu novio es el mayor honor que puedo tener😍. Hacerte feliz siempre ha sido y siempre será mi objetivo😍, cuando haya un día que no lo logre🙈, puedes venir aquí y leer esto: ERES UNA PERSONA MARAVILLOSA, UNA MUJER ÚNICA Y YO SOY MUY, PERO QUE MUUUUY, AFORTUNADO DE TENERTE EN MI VIDA🐧💖🐧. ";

    document.getElementById('home-header').className ='header-color'+t;
    document.getElementById('img-link').className = 'images-link img'+t;
    document.getElementById('pingu-gif').className = 'pingu-gif pingu-gif'+r;
    
     if (t >= 5 && t <= 10) {
      document.getElementById('blog-p').innerHTML = parrafo1;
       } else if (t >= 11 && t <= 15) {
        document.getElementById('blog-p').innerHTML = parrafo2;
       } else if (t >= 16 && t <= 19) {
        document.getElementById('blog-p').innerHTML = parrafo3;
       } else if (t >= 20) {
        document.getElementById('blog-p').innerHTML = parrafo4;
       } else { document.getElementById('blog-p').innerHTML = parrafo0}
}

cambiar_fondo_con_class();